services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6378:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

  playground:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edi-playground
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Redis=redis:6379
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
    depends_on:
      - redis
      - rabbitmq
    restart: unless-stopped