using EdiHybridCache.AppHost;

var builder = DistributedApplication.CreateBuilder(args);

// Redis: L2 cache and Pub/Sub channel for L1 invalidation
var redis = builder.AddRedis(AppHostConstants.RedisName);

// Playground project
// REDIS_CONNECTION: Aspire Redis requires authentication by default.
// We construct the StackExchange.Redis connection string with:
//   host:port,ssl=true,abortConnect=false,password=<auto-generated>
var redisPassword = redis.Resource.PasswordParameter ??
    throw new InvalidOperationException("Redis password was not generated.");
var playground = builder.AddProject<Projects.EdiHybridCache_Playground>(AppHostConstants.PlaygroundName)
    .WithReference(redis)
    .WithEnvironment(AppHostConstants.EnvRedisConnection,
        $"{redis.GetEndpoint("tcp").Property(EndpointProperty.HostAndPort)}{AppHostConstants.RedisSslSuffix}{redisPassword}");

builder.Build().Run();
