using EdiHybridCache.AppHost;

var builder = DistributedApplication.CreateBuilder(args);

// Redis: L2 cache
var redis = builder.AddRedis(AppHostConstants.RedisName);

// RabbitMQ: invalidation messaging with explicit credentials
var rabbitmqUserParam = builder.AddParameter(AppHostConstants.RabbitMqUserParamName, AppHostConstants.DefaultRabbitMqUsername);
var rabbitmqPasswordParam = builder.AddParameter(AppHostConstants.RabbitMqPasswordParamName, AppHostConstants.DefaultRabbitMqPassword);
var rabbitmq = builder.AddRabbitMQ(AppHostConstants.RabbitMqName, rabbitmqUserParam, rabbitmqPasswordParam);

// Playground project
// REDIS_CONNECTION: Aspire Redis requires authentication by default.
// We construct the StackExchange.Redis connection string with:
//   host:port,ssl=true,abortConnect=false,password=<auto-generated>
var redisPassword = redis.Resource.PasswordParameter ??
    throw new InvalidOperationException("Redis password was not generated.");
var rabbitmqUser = rabbitmq.Resource.UserNameParameter!;
var rabbitmqPassword = rabbitmq.Resource.PasswordParameter!;
var playground = builder.AddProject<Projects.EdiHybridCache_Playground>(AppHostConstants.PlaygroundName)
    .WithReference(redis)
    .WithReference(rabbitmq)
    .WithEnvironment(AppHostConstants.EnvRedisConnection,
        $"{redis.GetEndpoint("tcp").Property(EndpointProperty.HostAndPort)}{AppHostConstants.RedisSslSuffix}{redisPassword}")
    .WithEnvironment(AppHostConstants.EnvRabbitMqHost, rabbitmq.GetEndpoint("tcp").Property(EndpointProperty.Host))
    .WithEnvironment(AppHostConstants.EnvRabbitMqPort, rabbitmq.GetEndpoint("tcp").Property(EndpointProperty.Port))
    .WithEnvironment(AppHostConstants.EnvRabbitMqUsername, rabbitmqUser)
    .WithEnvironment(AppHostConstants.EnvRabbitMqPassword, rabbitmqPassword);

builder.Build().Run();
